Repository wecode-bootcamp-korea/40-1st-NI-We-Ke-backend, pull requests merged in 2022-12, with the labels that each got.

#1 초기세팅 완료
  .env.sample
  .gitignore
  app.js
  package-lock.json
  package.json
  src/controllers/auth.controller.js
  src/models/data-source.js
  src/routes/auth.router.js
  src/services/auth.service.js
  src/utils/validators.js
Labels: 수정 요청

#2 [ADD] 스키마 파일 생성완료
  db/migrations/20221206081752_create_categories_table.sql
  db/migrations/20221206081753_create_sizes_table.sql
  db/migrations/20221206081754_create_colors_table.sql
  db/migrations/20221206081756_create_types_table.sql
  db/migrations/20221206081757_create_users_table.sql
  db/migrations/20221206081920_create_details_table.sql
  db/migrations/20221206081921_create_products_table.sql
  db/migrations/20221206085945_create_status_table.sql
  db/migrations/20221206085946_create_orders_table.sql
  db/migrations/20221206085954_create_sales_table.sql
  db/migrations/20221206085955_create_product_options_table.sql
  db/migrations/20221206085956_create_product_option_images_table.sql
  db/migrations/20221206085957_create_carts_table.sql
  db/migrations/20221206085958_create_wishlists_table.sql
Labels: 멘토 리뷰 요청

#3 [40기 원승현] 로그인 회원가입 기능 구현
  app.js
  src/controllers/auth.controller.js
  src/models/user.dao.js
  src/routes/auth.router.js
  src/routes/index.js
  src/services/auth.service.js
  src/utils/validators.js
Labels: 멘토 리뷰 요청

#4 [40기 원승현]카테고리에 따른 상품 조회 기능 api 추가
  app.js
  src/controllers/product.controller.js
  src/models/product.dao.js
  src/routes/index.js
  src/routes/product.js
  src/services/product.service.js
Labels: 멘토 리뷰 요청

#7 [40기 박진주] Database 수정 (테이블 추가 및 column 수정)
  db/migrations/20221206081921_create_icons_table.sql
  db/migrations/20221206081922_create_products_table.sql
  db/migrations/20221206085945_create_statuses_table.sql
  db/migrations/20221206085958_create_wishlists_table.sql
  db/migrations/20221213085650_create_sales_table.sql
  db/migrations/20221213085753_create_reviews_table.sql
Labels: 멘토 리뷰 요청

#5 [40기 원승현]Feature/order
  src/controllers/order.controllers.js
  src/controllers/product.controller.js
  src/models/order.dao.js
  src/models/user.dao.js
  src/routes/index.js
  src/routes/order.router.js
  src/routes/product.router.js
  src/services/order.service.js
  src/services/product.service.js
  src/utils/auth.js
Labels: 멘토 리뷰 요청

#6 [40기 원승현]Feature/search/product name
  app.js
  src/models/product.models.js
  src/routes/index.js
  src/routes/product.router.js
  src/services/product.service.js
Labels: 멘토 리뷰 요청

#8 [40기 원승현]상세페이지 불러오기 기능 구현
  src/controllers/product.controller.js
  src/models/product.dao.js
  src/routes/index.js
  src/routes/product.router.js
  src/services/product.service.js
Labels: 멘토 리뷰 요청

#9 [40기 박진주] 장바구니 CRUD 완성
  .vscode/extensions.json
  app.js
  db/migrations/20221206085945_create_statuses_table.sql
  package-lock.json
  src/controllers/auth.controller.js
  src/controllers/cart.controller.js
  src/models/cart.dao.js
  src/models/product.dao.js
  src/models/user.dao.js
  src/routes/cart.router.js
  src/routes/index.js
  src/services/auth.service.js
  src/services/cart.service.js
  src/utils/auth.js
  src/utils/validators.js
Labels: Conflict 해결 요청, 수정 요청

#13 [40기 박진주] draw(응모) 제품 전체 조회 API
  src/controllers/draw.controller.js
  src/models/draw.dao.js
  src/routes/draw.router.js
  src/routes/index.js
  src/services/draw.service.js
Labels: 멘토 리뷰 요청

#15 [40기 박진주] Wishlist 추가 조회 기능
  src/controllers/wishlist.controller.js
  src/models/wishlist.dao.js
  src/routes/index.js
  src/routes/product.router.js
  src/routes/wishlist.router.js
  src/services/wishlist.service.js
Labels: 멘토 리뷰 요청
